/localization_module: 
  ros__parameters:
    common:
      run_on_mower: true # true时, 【map_directory_on_mower】参数会覆盖【map_directory】参数；false时还是由【map_directory】决定
      # map_directory_on_mower: "/home/firefly/fl_localization_ws/maps/"
      map_directory_on_mower: "/home/nb00085/maps/"
      cpu_id_on_mower: [4,5,6]
      
      init_module_status: 0 # 0: Module_IDLE, 1: Module_MAPPING,  2: Module_SEC_MAPPING, 3: Module_LOCALIZATION
      time_sync_en: false
      
      map_relative_to: 2 # -- 2: 使用绝对路径（recommanded）; --1: 相对路径，相对于 catkin workspace; --0: 相对路径，相对于catkin pkg; # disable---3: 相对路径，相对于 ${HOME};
      map_directory: "/home/nb00085/maps/" #保存地图的路径
      
      sub_topic_ctrl_cmd: "/flbot/localization_module/ctrl_cmd"
      pub_topic_module_status: "/flbot/localization_module/module_status"
      pub_topic_module_health: "/flbot/localization_module/module_health"
      pub_topic_module_loginfo: "/flbot/localization_module/log_info"
      pub_topic_slipping: "/flbot/localization_module/slipping_old"
      receive_lidar_freq: 10 # unit: hz
      slam_lose_rate_time_thr: 0.12 # unit: second

      check_delay: false
      before_downsample_size_thr: 3000 # 降采样前点个数不能小于3000个
      feats_down_size_thr: 100 # 降采样后的点个数不能小于200个
      cpu_id: [4, 5]

    extrinsic:    
      extrinsic_est_en:  false      # imu frame to laser frame, namely transform a point from laser into imu frame
      extrinsic_T: [ 0.0, -0.02329, 0.04412 ]   # T_imu_lidar
      extrinsic_R: [ 0.0,  0.0,  0.0]  # unit(degree), yaw, pitch, roll

      extrinsic_euler_IMU_in_lidar: [0.0, 0.0, 0.0] # unit(degree) yaw, pitch, roll
      #这个参数和上面的extrinsic_R是逆的关系

      # zhengfu bags
      # extrinsic_euler_lidar_in_baselink: [-90.0, 0.0, -5.0]  # unit(degree) yaw, pitch, roll

      # extrinsic_euler_lidar_in_baselink: [-90.645, 0.35, -3.448] # 转90度安装，172.18.0.16，tx=0.37, ty=0, tz=0.202

      extrinsic_euler_lidar_in_baselink: [0.510998, 0.161714, -0.879601] # 正着装机器，172.18.3.231
      
      # zhengfu bags
      # Lidar_In_Wheel: [1.0,  0.0,  0.0,  0.306,
      #                   0.0,  1.0,  0.0,  0.0,
      #                   0.0,  0.0,  1.0,  0.156,
      #                   0.0,  0.0,  0.0,  1.0]
      
      #正着装机器，172.18.3.231
      Lidar_In_Wheel: [1.0,  0.0,  0.0,  0.274,
                        0.0,  1.0,  0.0,  0.0,
                        0.0,  0.0,  1.0,  0.203,
                        0.0,  0.0,  0.0,  1.0]
      #雷达点云已经在驱动中转换成了和base_link朝向一致的点云，原点的位置还在实际雷达处

    localization:
      cloud_leaf_size_localize: 0.3
      fgicp_peroid_sec: 1.0  #定位线程1hz运行，每3s匹配一次，单位： 秒
      fgicp_score_fail_thr: 0.3
      fgicp_score_low_accuracy_thr: 0.07
      fgicp_fail_count_thr: 3
      fgicp_low_accuracy_count_thr: 1800

    lidar_preproc:
      lidar_type: 1 # 1: livox-mid360  # 2: robosense-Airy 
      sub_lidar_topic: "/livox/lidar"
      sub_imu_topic: "/livox/imu"

      blind_distance: 0.5 # 忽略掉距离雷达小于这个阈值的点
      max_distance: 70.0
      z_range: [-5.0, 20.0] # z > 20m点在预处理阶段被过滤掉了

      keep_lidar_num_before_curr: 3 # lidar buffer size
      cloud_size_to_keep: 3500  # 第一步降采样（预处理阶段）只保留3500个点

      extract_cloud_method: 0 ## # 没有起作用  (当前可选0,1,2) #-0:间隔采样 #-1: voxel #-2: 间隔采样&voxel  #-3: feature
      point_filter_num: 6 # # 没有起作用 每隔多少个点采样一个点,  
      ring_filter_num: 1  # 没有起作用

      leafsize: 0.5 # extract_cloud_method == 2 时, voxel 参数

      leafsize_vec: [0.2, 0.8] # voxel 所需参数
      voxel_region_xyz: [-10.0, 10.0, -10.0, 10.0, -1.0, 15.0]  # order: xmin, xmax, ymin, ymax, zmin, zmax
      boundary_z: 3.0 # init: m
      
      time_cost_thr_print: 10.0 # unit: ms，雷达预处理阶段耗时阈值

    mapping:
      acc_cov: 0.017573468691815922
      gyr_cov: 0.01524654486781841 
      b_acc_cov: 0.00025566293746767606
      b_gyr_cov: 0.0007414029109004667

      cloud_leaf_size: 0.5      # lio对去完畸变后的点云进行的voxel downsize

      key_frame_distance: 1.0   # unit: m     # 大于此距离为关键帧
      key_frame_angle: 0.2      # unit: rad   # 大于此角度为关键帧
      loopSearchDistance: 1.5
      loopSearchTimeDiff: 30.0  # unit: sec
      loopSearchSkipKey: 5  # 跳过的关键帧数， 间隔帧数小于 loopSearchSkipKey ，不参与回环检测搜索
      loopIcpScore: 0.3

      save_map_resolution: 0.1 # unit: m

    re_localization:
      score_thr: 0.5
      time_out_thr: 30 # unit: second, 超过 time_out_thr，还未重定位成功，认为重定位失败

    ikdtree:
      cube_len: 400.0
      det_range: 40.0
      kdTreeReconstructRadius: 400.0
      kdTreeReconstructKeyFrameLeafSize: 10.0
      kdTreeReconstructPointLeafSize: 1.0
      map_leaf_size: 0.5  
      
    detect_slip: 
      detect_window_time_range: 2.0 # unit: second
      slipping_count_thr: 5 # 连续帧数超过距离阈值，即为打滑, 20hz 前提下
      slipping_dist_thr: 0.15 # unit: m
