# 获取 GIT 信息
execute_process(COMMAND git rev-parse --abbrev-ref HEAD
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_BRANCH OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND git describe --tags --abbrev=0
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_TAG OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET)

execute_process(COMMAND git rev-parse HEAD
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND git log -1 --pretty=format:%an
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_AUTHOR OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND git log -1 --pretty=format:%ad
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_DATE OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND git log -1 --pretty=format:%s
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_MESSAGE OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND git status --porcelain
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_STATUS OUTPUT_STRIP_TRAILING_WHITESPACE)

if(GIT_STATUS STREQUAL "")
    set(GIT_DIRTY "NO")
else()
    set(GIT_DIRTY "YES")
endif()

execute_process(COMMAND git rev-list --count HEAD
    WORKING_DIRECTORY ${SRC_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_COUNT OUTPUT_STRIP_TRAILING_WHITESPACE)

# 写文件
configure_file(${TEMPLATE_FILE} ${OUTPUT_FILE} @ONLY)
